### 새 사용자 생성
POST http://localhost:3000/auth/signup
Content-type: application/json

{
  "email":"wndtlr1024@gmail.com",
  "password":"sdsdfsf"
}

### 사용자 조회
GET http://localhost:3000/auth/1

### 이메일로 모든 사용자 찾기
GET http://localhost:3000/auth?email=wndtlr1024@gmail.com
